import fs from 'node:fs';
import path from 'node:path';
import { AgentRegistry } from '@/scanner/registry';
import { loadConfig } from '@/scanner/configLoader';
import { MOCK_AGENTS, MOCK_PIPELINES } from '@/mocks/agents';

let cachedRegistry: AgentRegistry | null = null;
let lastScanTime = 0;
const DEV_CACHE_TTL = 5000;

export async function getRegistry(): Promise<AgentRegistry> {
  const isMock = process.env.ARCHON_MOCK === 'true';
  const isDev = process.env.NODE_ENV !== 'production';

  // In dev mode (not mock), auto-invalidate after TTL
  if (cachedRegistry && isDev && !isMock) {
    if (Date.now() - lastScanTime > DEV_CACHE_TTL) {
      cachedRegistry = null;
    }
  }

  if (cachedRegistry) return cachedRegistry;

  // 1. Mock mode — use embedded mock data
  if (isMock) {
    const registry = AgentRegistry.fromMocks(MOCK_AGENTS, MOCK_PIPELINES);
    lastScanTime = Date.now();
    cachedRegistry = registry;
    return registry;
  }

  // 2. Production — try baked JSON (generated by `archon build`)
  const bakedPath = path.resolve(process.cwd(), '.archon-data.json');
  if (!isDev && fs.existsSync(bakedPath)) {
    try {
      const raw = JSON.parse(fs.readFileSync(bakedPath, 'utf-8'));
      const registry = AgentRegistry.fromMocks(raw.agents ?? [], raw.pipelines ?? []);
      console.log('[archon] Loaded baked data from .archon-data.json');
      lastScanTime = Date.now();
      cachedRegistry = registry;
      return registry;
    } catch (err) {
      console.warn('[archon] Failed to read baked data, falling back to scan');
    }
  }

  // 3. Dev mode — scan agent files via subprocess
  const projectRoot = process.env.ARCHON_PROJECT_ROOT || process.cwd();
  const config = await loadConfig(projectRoot);
  const registry = new AgentRegistry(config, projectRoot);
  await registry.scan();

  lastScanTime = Date.now();
  cachedRegistry = registry;
  return registry;
}

/** Force re-scan on next request */
export function invalidateRegistry() {
  cachedRegistry = null;
}
